baseurl                 = "https://www.kyawtnt.com/"
DefaultContentLanguage  = "en"
title = "Kyaw T&T "
theme                   = "travel-tnt"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = true
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false
  images = ["/img/IMG-1abcaa994feb453f9123ada438ccc7e7-V.jpg"]

  [params.meta]
   description = " Kyaw Travel and Tour "
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Kyaw T&T"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Kyaw Travel And Tour"
    paragraph             = "Official licensed tour guide"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = ""
      shape               = "circle"
      width               = ""
      alt                 = ""

  [params.sidebar]
    about               = "I m a friendly, funny, kind, enthusiastic tour guide in Myanmar."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Trips"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  
  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.de]
    LanguageCode        = "de"
    LanguageName        = "Deutsche"
    title               = "Kyaw Reisen und Tour"
    description         = ""
    weight              = 2

    [Languages.de.params.intro]
    header                = "Kyaw Reisen und Tour"
    paragraph             = "Offizieller lizenzierter Reiseleiter"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [Languages.de.params.intro.pic]
      src                 = "/img/logo.jpg"
      shape               = "circle"
      width               = ""
      alt                 = ""
    [Languages.de.params.sidebar]
    about               = "I m a friendly, funny, kind, enthusiastic tour guide in Myanmar."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true
    [[Languages.de.menu.main]]
      name              = "Accueil"
      identifier        = "home"
      url               = "/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.de.menu.main]]
      name              = "Über"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.de.menu.main]]
      name              = "Reisen"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

   
    [[Languages.de.menu.main]]
      name              = "Kontakt"
      identifier        = "contact"
      url               = "/contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

 

  




[social]

 
 
  # Social Networks
  facebook              = "kyawnay.myolatt/"
  whatsapp              = "+ 959972542335" # WhatsApp Number
  email                 = "kyawnaymyolatt7@gmail.com"
  instagram             = "https://www.instagram.com/p/CD-ZpR_lvR1/?igshid=1io6wbhmw53bg"
